backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "Globals"
    label: "globals"
    files:
      - file: "content/global/footer.json"
        label: "Footer"
        name: "footer"
        fields: 
          - {label: "Title", name: "footertitle", widget: "string"}
          - {label: "Description", name: "footerdesc", widget: "string"}
          - {label: "Copyright", name: "copyright", widget: "string"}
          - label: "Footer Links"
            name: "footer link"
            widget: "object"
            collapsed: false
            fields:
            - label: "Links"
              name: "linklist"
              widget: "list"
              collapsed: true
              max: 4
              min: 1
              fields:
              - {label: "Link Text", name: "linktext", widget: "string"}
              - {label: "Link Path", name: "linkpath", widget: "string"}
  - name: "Posts"
    label: "Posts"
    files:
      - file: "content/posts/blog.json"
        label: "Blog"
        name: "blog"
        fields: 
          - {label: "Name", name: "name", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Featured Image", name: "thumbnail", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}